// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/discount.proto
// </auto-generated>
namespace Discount.Grpc
{
    internal class GetDiscountRequest
    {
    }
}